---
- name: download Oracle JDK
  command: bash -c "cd /root && wget http://ns2.1888.spb.ru/jdk-8u40-linux-x64.rpm" creates=/root/jdk-8u40-linux-x64.rpm
  when: ansible_os_family == 'RedHat'

- name: install Oracle JDK
  yum: name=/root/jdk-8u40-linux-x64.rpm state=present
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'
