---
- name: install wget
  yum: name=wget state=present
  when: ansible_os_family == 'RedHat'

- name: download Zulu JDK
  shell: "cd /root && wget https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-jdk8.0.232-linux.x86_64.rpm"
  args:
     creates: /root/zulu8.42.0.23-ca-jdk8.0.232-linux.x86_64.rpm
  when: ansible_os_family == 'RedHat'

- name: install Zulu JDK
  yum: name=/root/zulu8.42.0.23-ca-jdk8.0.232-linux.x86_64.rpm state=present
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
