---
- name: install wget
  yum: name=wget state=present
  when: ansible_os_family == 'RedHat'

- name: download Oracle JDK
  shell: "cd /root && wget --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"
  args:
     creates: /root/jdk-8u131-linux-x64.rpm
  when: ansible_os_family == 'RedHat'

- name: install Oracle JDK
  yum: name=/root/jdk-8u131-linux-x64.rpm state=present
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'
